In [1]:
import numpy as np

### In Class: 
   ### Problem 1: Simple Linear Regression - Calculate the Sample Correlation Coefficient

In [2]:
x = [1,3,5,7,9]
y = [2,6,10,14,18]

In [3]:
#Calculate average of x
x_bar = np.mean(x)
x_bar

5.0

In [4]:
#Calculate standard deviation of x
S_x = round(np.std(x, ddof = 1),2)
S_x

3.16

In [5]:
#Calculate average of y
y_bar = np.mean(y)
y_bar

10.0

In [6]:
#Calculate standard devaition of y
S_y = round(np.std(y, ddof = 1),2)
S_y

6.32

In [7]:
#Calculate variance of x
x_var = np.var(x, ddof=1)
x_var

10.0

In [9]:
#Covariance the long way
sigma_xy = 0
for i in range(len(x)): 
    sigma_xy += ((x[i] - x_bar)*(y[i] - y_bar))

cov = sigma_xy/(len(x)-1)
    
cov

20.0

In [10]:
#covarainnce the short way
xandy = [x,y]
print("Format list so numpy can process", xandy)
cov2 = np.cov(xandy)
cov2

Format list so numpy can process [[1, 3, 5, 7, 9], [2, 6, 10, 14, 18]]


array([[10., 20.],
       [20., 40.]])

In [11]:
#Calculate the correlation coeffeicient
r_xy = (cov/x_var)*(S_x/S_y)
r_xy

1.0

In [12]:
#Or in one line using numpy 
cocoeff = np.corrcoef(x,y)
cocoeff

array([[1., 1.],
       [1., 1.]])

In [15]:
y = [7,12,42,19,66]

In [13]:
#Change the y values by multiplying by -1
for i in range(len(y)):
    y[i] = y[i] * -1
y

[-2, -6, -10, -14, -18]

In [16]:
cocoeff2 = np.corrcoef(x,y)
cocoeff2

array([[1.        , 0.80506217],
       [0.80506217, 1.        ]])

### Problem 2: Linearize an exponential function 

In [17]:
x = [0.1,0.3,0.5,0.7,0.9]
y = [7.288475201562036,24.19858985765178,80.34214769275067,266.7453241637004,885.6256648167487]

In [18]:
# Linearize y
ln_y = []
for i in y: 
    ln_y.append(np.log(i))
ln_y

[1.9862943611198907,
 3.1862943611198906,
 4.386294361119891,
 5.58629436111989,
 6.786294361119891]

In [19]:
x_bar = np.mean(x)
x_bar

0.5

In [20]:
y_bar = round(np.mean(ln_y),2)
y_bar

4.39

In [21]:
S_x = round(np.std(x, ddof=1),2)
S_x

0.32

In [22]:
S_y = round(np.std(ln_y, ddof=1),2)
S_y

1.9

In [23]:
x_var = np.var(x, ddof=1)
x_var

0.1

In [24]:
sigma_xy = 0
for i in range(len(x)): 
    sigma_xy += ((x[i] - x_bar)*(ln_y[i] - y_bar))

cov = sigma_xy/(len(x)-1)
    
cov

0.6000000000000001

In [25]:
#covarainnce the short way
xandy = [x,ln_y]
print("Format list so numpy can process", xandy)
cov2 = np.cov(xandy)
cov2

Format list so numpy can process [[0.1, 0.3, 0.5, 0.7, 0.9], [1.9862943611198907, 3.1862943611198906, 4.386294361119891, 5.58629436111989, 6.786294361119891]]


array([[0.1, 0.6],
       [0.6, 3.6]])

In [26]:
beta_hat = round(cov/x_var,1)
beta_hat

6.0

In [27]:
#alpha_hat = y_bar - beta_hat * x_bar
alpha_hat = round(y_bar - beta_hat * x_bar,2)
alpha_hat

1.39

In [28]:
#de linearize: 
coeff = round(np.exp(alpha_hat),2)
coeff

4.01

### Problem 3 : Solve the Gradient Descent Problem

In [33]:
step = 0.01
pos = [1,2,"f(x,y)"] #f(x,y) = x**2 + y**2)
for i in range(5):
    pos[0] = round((pos[0] - (step * 2 * pos[0])),2)
    pos[1] = round((pos[1] - (step * 2 * pos[1])),2)
    pos[2] = round((pos[0]**2 + pos[1]**2),2)
    
    print("Step {}".format(i))
    print (pos)
    print ("\n")
    
    

Step 0
[0.98, 1.96, 4.8]


Step 1
[0.96, 1.92, 4.61]


Step 2
[0.94, 1.88, 4.42]


Step 3
[0.92, 1.84, 4.23]


Step 4
[0.9, 1.8, 4.05]


