In [1]:
import numpy as np

### In Class: 
   ### Problem 1: Simple Linear Regression - Calculate the Sample Correlation Coefficient

In [54]:
x = [1,3,5,7,9]
y = [2,6,10,14,18]

In [43]:
#Calculate average of x
x_bar = np.mean(x)
x_bar

5.0

In [44]:
#Calculate standard deviation of x
S_x = round(np.std(x, ddof = 1),2)
S_x

3.16

In [45]:
#Calculate average of y
y_bar = np.mean(y)
y_bar

10.0

In [46]:
#Calculate standard devaition of y
S_y = round(np.std(y, ddof = 1),2)
S_y

6.32

In [47]:
#Calculate variance of x
x_var = np.var(x, ddof=1)
x_var

10.0

In [48]:
#Covariance the long way
sigma_xy = 0
for i in range(len(x)): 
    sigma_xy += ((x[i] - x_bar)*(y[i] - y_bar))

cov = sigma_xy/(len(x)-1)
    
cov

20.0

In [49]:
#covarainnce the short way
xandy = [x,y]
print("Format list so numpy can process", xandy)
cov2 = np.cov(xandy)
cov2

Format list so numpy can process [[1, 3, 5, 7, 9], [2, 6, 10, 14, 18]]


array([[10., 20.],
       [20., 40.]])

In [50]:
#Calculate the correlation coeffeicient
r_xy = (cov/x_var)*(S_x/S_y)
r_xy

1.0

In [51]:
#Or in one line using numpy 
cocoeff = np.corrcoef(x,y)
cocoeff

array([[1., 1.],
       [1., 1.]])

In [52]:
#Change the y values by multiplying by -1
for i in range(len(y)):
    y[i] = y[i] * -1
y

[-2, -6, -10, -14, -18]

In [53]:
cocoeff2 = np.corrcoef(x,y)
cocoeff2

array([[ 1., -1.],
       [-1.,  1.]])

### Problem 2: Linearize an exponential function 

In [60]:
x = [0.1,0.3,0.5,0.7,0.9]
y = [7.288475201562036,24.19858985765178,80.34214769275067,266.7453241637004,885.6256648167487]

In [62]:
# Linearize y
ln_y = []
for i in y: 
    ln_y.append(np.log(i))
ln_y

[1.9862943611198907,
 3.1862943611198906,
 4.386294361119891,
 5.58629436111989,
 6.786294361119891]

In [64]:
x_bar = np.mean(x)
x_bar

0.5

In [67]:
y_bar = round(np.mean(ln_y),2)
y_bar

4.39

In [71]:
S_x = round(np.std(x, ddof=1),2)
S_x

0.32

In [72]:
S_y = round(np.std(ln_y, ddof=1),2)
S_y

1.9

In [73]:
x_var = np.var(x, ddof=1)
x_var

0.1

In [74]:
sigma_xy = 0
for i in range(len(x)): 
    sigma_xy += ((x[i] - x_bar)*(ln_y[i] - y_bar))

cov = sigma_xy/(len(x)-1)
    
cov

0.6000000000000001

In [75]:
#covarainnce the short way
xandy = [x,ln_y]
print("Format list so numpy can process", xandy)
cov2 = np.cov(xandy)
cov2

Format list so numpy can process [[0.1, 0.3, 0.5, 0.7, 0.9], [1.9862943611198907, 3.1862943611198906, 4.386294361119891, 5.58629436111989, 6.786294361119891]]


array([[0.1, 0.6],
       [0.6, 3.6]])

In [78]:
beta_hat = round(cov/x_var,1)
beta_hat

6.0

In [80]:
#alpha_hat = y_bar - beta_hat * x_bar
alpha_hat = round(y_bar - beta_hat * x_bar,2)
alpha_hat

1.39

In [83]:
#de linearize: 
coeff = round(np.exp(alpha_hat),2)
coeff

4.01

### Problem 3 : Solve the Gradient Descent Problem

In [108]:
step = 0.1
pos = [1,2,"f(x,y)"] #f(x,y) = x**2 + y**2)
for i in range(10):
    pos[0] = round((pos[0] - (step * 2 * pos[0])),2)
    pos[1] = round((pos[1] - (step * 2 * pos[1])),2)
    pos[2] = round((pos[0]**2 + pos[1]**2),2)
    
    print("Step {}".format(i))
    print (pos)
    print ("\n")
    
    

Step 0
[0.8, 1.6, 3.2]


Step 1
[0.64, 1.28, 2.05]


Step 2
[0.51, 1.02, 1.3]


Step 3
[0.41, 0.82, 0.84]


Step 4
[0.33, 0.66, 0.54]


Step 5
[0.26, 0.53, 0.35]


Step 6
[0.21, 0.42, 0.22]


Step 7
[0.17, 0.34, 0.14]


Step 8
[0.14, 0.27, 0.09]


Step 9
[0.11, 0.22, 0.06]


